networks:
  homepage:
    name: homepage-network
    driver: bridge

services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - VERSION=1 # Allow access to viewing version
      - EVENTS=1 # Allow access to viewing events
      - PING=1 # Allow access to viewing ping
      - POST=0 # Disallow any POST operations (effectively read-only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    networks:
      - homepage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:2375/version"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
  
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: '*' # see gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: 1000 # default user id
      PGID: 1000 # default group id
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./assets:/app/public/assets
    networks:
      - homepage
    depends_on:
      dockerproxy:
        condition: service_healthy
    restart: unless-stopped
