networks:
  adguard:
    name: adguard-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    environment:
      PUID: 1000
      PGID: 1000
    env_file:
      - ../.env
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    networks:
      adguard:
        ipv4_address: 172.25.0.2
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8095:3000/tcp
    restart: unless-stopped
    labels:
      - homepage.group=Tools
      - homepage.name=AdGuard Home
      - homepage.icon=https://avatars.githubusercontent.com/u/8361145
      - homepage.href=http://${CUSTOM_LOCAL_HOST:-localhost}:8095
      - homepage.description=Network-wide ads & trackers blocking DNS server
