networks:
  tor:
    name: tor-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24

services:
  snowflake-proxy:
    image: containers.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake:latest
    container_name: snowflake-proxy
    networks:
      tor:
        ipv4_address: 172.23.0.2
    restart: always
    labels:
      - homepage.group=Privacy
      - homepage.name=Tor Snowflake
      - homepage.icon=https://snowflake.torproject.org/static/images/tor-browser-icon.png
      - homepage.href=https://snowflake.torproject.org/
      - homepage.description=Free your connection
